# Generated by Django 4.2.4 on 2023-08-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_tag_order_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(to='bookstore.tag'),
        ),
    ]
